### ISSUE TITLE
Pyjnius doesn't compile with cython 0.24

### ISSUE THREAD

**Issue by inclement** [kivy/pyjnius#219]
Looks like there's some incorrect typecasting syntax that presumably didn't previously raise a compile error.

Here's a section of the log, there are a lot of similar problems:

    jnius/jnius.c:9710:133: error: expected expression before ‘)’ token
     v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"doubleValue"), ((const_char *)"()D"));
                                                                                                                               ^
    jnius/jnius.c:9761:102: error: expected expression before ‘)’ token
         __pyx_v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"shortValue"), ((const_char *
                                                                                                          ^
    jnius/jnius.c:9761:132: error: expected expression before ‘)’ token
     _v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"shortValue"), ((const_char *)"()S"));
                                                                                                                               ^
    jnius/jnius.c:9812:102: error: expected expression before ‘)’ token
         __pyx_v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"booleanValue"), ((const_char
                                                                                                          ^
    jnius/jnius.c:9812:134: error: expected expression before ‘)’ token
     _retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"booleanValue"), ((const_char *)"()Z"));

**Comment by kived** [comment]
This is already fixed in master. ;)

**Comment by inclement** [comment]
Oh, jolly good. I did wonder why I never hit it with p4a!
