### PR TITLE
use real const

### LINKED ISSUE #219: Pyjnius doesn't compile with cython 0.24
Looks like there's some incorrect typecasting syntax that presumably didn't previously raise a compile error.

Here's a section of the log, there are a lot of similar problems:

    jnius/jnius.c:9710:133: error: expected expression before ‘)’ token
     v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"doubleValue"), ((const_char *)"()D"));
                                                                                                                               ^
    jnius/jnius.c:9761:102: error: expected expression before ‘)’ token
         __pyx_v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"shortValue"), ((const_char *
                                                                                                          ^
    jnius/jnius.c:9761:132: error: expected expression before ‘)’ token
     _v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"shortValue"), ((const_char *)"()S"));
                                                                                                                               ^
    jnius/jnius.c:9812:102: error: expected expression before ‘)’ token
         __pyx_v_retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"booleanValue"), ((const_char
                                                                                                          ^
    jnius/jnius.c:9812:134: error: expected expression before ‘)’ token
     _retmeth = (__pyx_v_j_env[0])->GetMethodID(__pyx_v_j_env, __pyx_v_retclass, ((const_char *)"booleanValue"), ((const_char *)"()Z"));

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33104082-pyjnius-doesn-t-compile-with-cython-0-24?utm_campaign=plugin&utm_content=tracker%2F77133&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F77133&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kived**
Fixes #219.

### CODE REVIEW

**Comment by kived** [comment]
Nevermind, was on an older version of master. Ignore this.
