### ISSUE TITLE
setup.py doesn't work with Python 3.5

### ISSUE THREAD

**Issue by jhidding** [kivy/pyjnius#199]
Running "python setup.py install" with Python 3.5 gives the following error:
... AttributeError: 'str' object has no attribute 'decode' 
The bug is in the 'getenv' function, where the result of os.environ.get is being decoded. The error is only triggered in certain cases, installing on a clean system.
##

**Comment by jk1ng** [comment]
I haven't verified this yet, but I suspect that os.environ returns unicode across multiple platforms. I've managed to install* it by editing out the .decode() call.

*Now I am having an issue with:

>     from .jnius import *
>     ImportError: DLL load failed: The specified module could not be found.

**Comment by jk1ng** [comment]
I'd like to add that a workaround for my issue was ensuring that I had the right PATH and JAVA_HOME environment variable set. See Issue #197

**Comment by KeyWeeUsr** [comment]
Two issues basically. One closed by #200 the `decode()`. Another one has a documentation section added via #361.
